import { db } from './index.ts';
import { trades } from './schema.ts';
import { v4 as uuidv4 } from 'uuid';

async function seedHistory2() {
  console.log("Seeding extended betting history (Mar 5 - Mar 17)...");

  const extendedTrades = [
    // === MARCH 17, 2026 (additional) ===
    {
      id: uuidv4(),
      matchup: "MIL Bucks vs CLE Cavaliers + MIN Timberwolves vs PHX Suns + SAC Kings vs SA Spurs",
      mathEv: -0.03,
      dissonanceScore: 0.40,
      prospectTheoryRead: "NBA 3-leg spread parlay - all covered but tight margins",
      selection: "Cavaliers -2.5 / Suns +8.5 / Spurs -9.5",
      alphaEdge: "NEUTRAL",
      kellySizing: "2.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-17T20:57:00"),
    },
    {
      id: uuidv4(),
      matchup: "CHA Hornets vs MIA Heat + MIN Timberwolves vs PHX Suns",
      mathEv: 0.03,
      dissonanceScore: 0.35,
      prospectTheoryRead: "NBA 2-leg: Hornets ML + Suns spread",
      selection: "Hornets ML / Suns +6.5",
      alphaEdge: "NEUTRAL",
      kellySizing: "2.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-17T18:38:00"),
    },
    {
      id: uuidv4(),
      matchup: "WSH Wizards vs DET Pistons + CHA Hornets vs MIA Heat + ORL Magic vs OKC Thunder + NY Knicks vs IND Pacers + MIN Wolves vs PHX Suns + MIL Bucks vs CLE Cavs",
      mathEv: -0.30,
      dissonanceScore: 0.75,
      prospectTheoryRead: "NBA 6-leg spread parlay @13.25 - high variance play",
      selection: "Pistons -15.5 / Hornets -1.5 / Magic +10.5 / Knicks -10.5 / Wolves +3.5 / Bucks +18.5",
      alphaEdge: "FADE",
      kellySizing: "0.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-17T18:13:00"),
    },
    {
      id: uuidv4(),
      matchup: "Manchester City vs Real Madrid (UCL)",
      mathEv: 0.35,
      dissonanceScore: 0.20,
      prospectTheoryRead: "UCL single longshot ML - Real Madrid value @6.00",
      selection: "Real Madrid ML @6.00",
      alphaEdge: "SHARP",
      kellySizing: "2.5%",
      actualOutcome: "WIN",
      timestamp: new Date("2026-03-17T13:36:00"),
    },
    {
      id: uuidv4(),
      matchup: "UCL: Man City vs Real Madrid + Chelsea vs PSG + Arsenal vs Leverkusen",
      mathEv: 0.06,
      dissonanceScore: 0.30,
      prospectTheoryRead: "UCL 3-leg totals/handicap parlay (Leverkusen leg voided)",
      selection: "Man City/RM U4.5 / Chelsea/PSG O2.5 / Leverkusen +2 AH (voided)",
      alphaEdge: "SHARP",
      kellySizing: "5.0%",
      actualOutcome: "WIN",
      timestamp: new Date("2026-03-17T13:40:00"),
    },
    {
      id: uuidv4(),
      matchup: "UCL: Sporting vs Bodo + Man City vs Real Madrid + Chelsea vs PSG",
      mathEv: -0.08,
      dissonanceScore: 0.55,
      prospectTheoryRead: "UCL 3-leg with Sporting BTTS - risky leg killed it",
      selection: "Sporting BTTS / Man City/RM U4.5 / Chelsea/PSG O2.5",
      alphaEdge: "NEUTRAL",
      kellySizing: "2.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-17T13:36:01"),
    },

    // === MARCH 15, 2026 ===
    {
      id: uuidv4(),
      matchup: "NY Knicks vs GS Warriors + SAC Kings vs Utah Jazz",
      mathEv: -0.25,
      dissonanceScore: 0.70,
      prospectTheoryRead: "NBA props 6-leg parlay @7.52 - player props across 2 games",
      selection: "Anunoby O13.5 PTS / Brunson O20.5 PTS / Gui Santos O20.5 PRA / Sensabaugh O17.5 PTS / Raynaud O23.5 PR / DeRozan O17.5 PTS",
      alphaEdge: "FADE",
      kellySizing: "0.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-15T17:20:00"),
    },
    {
      id: uuidv4(),
      matchup: "Dominican Republic vs USA (WBC)",
      mathEv: 0.10,
      dissonanceScore: 0.30,
      prospectTheoryRead: "WBC underdog ML - DR at home, big $25 stake",
      selection: "Dominican Republic ML @2.03",
      alphaEdge: "SHARP",
      kellySizing: "12.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-15T15:46:00"),
    },
    {
      id: uuidv4(),
      matchup: "Dominican Republic vs USA (WBC)",
      mathEv: 0.08,
      dissonanceScore: 0.35,
      prospectTheoryRead: "WBC DR ML double-down after line moved",
      selection: "Dominican Republic ML @1.99",
      alphaEdge: "NEUTRAL",
      kellySizing: "5.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-15T18:02:00"),
    },
    {
      id: uuidv4(),
      matchup: "PHI 76ers vs POR Trail Blazers",
      mathEv: -0.20,
      dissonanceScore: 0.75,
      prospectTheoryRead: "NBA SGP 6-leg player props @10.00 - too many legs",
      selection: "Edgecombe O15.5 PTS / Payne O7.5 PTS / 76ers +8.5 / Clingan O19.5 PR / Henderson O9.5 PTS / Grimes O15.5 PTS",
      alphaEdge: "FADE",
      kellySizing: "0.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-15T17:01:00"),
    },

    // === MARCH 14, 2026 ===
    {
      id: uuidv4(),
      matchup: "BOS Celtics vs WSH Wizards",
      mathEv: -0.10,
      dissonanceScore: 0.55,
      prospectTheoryRead: "NBA SGP 3-leg props - Brown leg missed",
      selection: "Trae Young O10.5 PTS / Tatum O17.5 PTS / Brown O20.5 PTS @2.55",
      alphaEdge: "NEUTRAL",
      kellySizing: "5.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-14T16:23:00"),
    },
    {
      id: uuidv4(),
      matchup: "ATL Hawks vs MIL Bucks + SA Spurs vs CHA Hornets",
      mathEv: -0.15,
      dissonanceScore: 0.65,
      prospectTheoryRead: "NBA props parlay 5-leg across 2 games @5.59",
      selection: "J.Johnson O36.5 PRA / McCollum O13.5 PTS / NAW O14.5 PTS / Castle O25.5 PRA / Miller O16.5 PTS",
      alphaEdge: "FADE",
      kellySizing: "2.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-14T13:51:00"),
    },
    {
      id: uuidv4(),
      matchup: "ATL Hawks vs MIL Bucks + SA Spurs vs CHA Hornets",
      mathEv: 0.02,
      dissonanceScore: 0.35,
      prospectTheoryRead: "NBA 2-leg spread - Hawks covered, Hornets didn't",
      selection: "Hawks -5.5 / Hornets +11.5",
      alphaEdge: "NEUTRAL",
      kellySizing: "2.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-14T13:48:00"),
    },
    {
      id: uuidv4(),
      matchup: "Real Madrid vs Elche + West Ham vs Man City + Zverev vs Sinner + Alcaraz vs Medvedev + Sabalenka vs Rybakina",
      mathEv: -0.05,
      dissonanceScore: 0.55,
      prospectTheoryRead: "Soccer/Tennis 5-leg mix @5.23 - Sabalenka leg lost",
      selection: "RM/Elche O2.5 / WHU/City O2.5 / Sinner ML / Alcaraz ML / Sabalenka ML",
      alphaEdge: "NEUTRAL",
      kellySizing: "1.8%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-14T13:45:00"),
    },

    // === MARCH 10, 2026 ===
    {
      id: uuidv4(),
      matchup: "PHI 76ers vs MEM + MIA Heat vs WSH + BKN Nets vs DET + ATL Hawks vs DAL + HOU Rockets vs TOR + SA Spurs vs BOS",
      mathEv: -0.10,
      dissonanceScore: 0.60,
      prospectTheoryRead: "NBA 6-leg spread parlay @7.79 - all dogs covered but one",
      selection: "76ers +2.5 / Wizards +22.5 / Nets +20.5 / Mavs +16.5 / Rockets +2.5 / Celtics +10.5",
      alphaEdge: "NEUTRAL",
      kellySizing: "2.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-10T17:54:00"),
    },
    {
      id: uuidv4(),
      matchup: "UCL: Galatasaray vs Liverpool + Atletico vs Tottenham + Newcastle vs Barcelona + Atalanta vs Bayern",
      mathEv: 0.02,
      dissonanceScore: 0.45,
      prospectTheoryRead: "UCL 4-leg: DC + Asian totals @4.31",
      selection: "Galatasaray DC / Atletico O1.5 / Newcastle/Barca O2.5 / Atalanta/Bayern O2.5",
      alphaEdge: "NEUTRAL",
      kellySizing: "2.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-10T12:54:00"),
    },
    {
      id: uuidv4(),
      matchup: "UCL: Galatasaray vs Liverpool + Newcastle vs Barcelona + Atalanta vs Bayern + Atletico vs Tottenham",
      mathEv: 0.01,
      dissonanceScore: 0.45,
      prospectTheoryRead: "UCL 4-leg: Liverpool DC + BTTS + overs @3.09",
      selection: "Liverpool DC / Newcastle/Barca BTTS / Atalanta/Bayern O2.5 / Atletico DNB",
      alphaEdge: "NEUTRAL",
      kellySizing: "5.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-10T12:28:00"),
    },
    {
      id: uuidv4(),
      matchup: "UCL: Galatasaray vs Liverpool + Newcastle vs Barcelona + Atalanta vs Bayern + Atletico vs Tottenham",
      mathEv: -0.05,
      dissonanceScore: 0.55,
      prospectTheoryRead: "UCL 4-leg all Asian overs @6.11 - Galatasaray game ruined it",
      selection: "Gala/Liverpool O2.5 / Newcastle/Barca O2.5 / Atalanta/Bayern O2.5 / Atletico/Spurs O2.5",
      alphaEdge: "NEUTRAL",
      kellySizing: "1.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-10T12:23:00"),
    },

    // === MARCH 8, 2026 ===
    {
      id: uuidv4(),
      matchup: "LA Lakers vs NY Knicks + SA Spurs vs HOU Rockets + SAC Kings vs CHI Bulls",
      mathEv: -0.30,
      dissonanceScore: 0.80,
      prospectTheoryRead: "NBA 6-leg props + spreads @18.87 - too ambitious",
      selection: "Brunson O21.5 PTS / Anunoby O1.5 3PM / Spurs -5.5 / Fox O13.5 PTS / Bulls -1.5 / Buzelis O15.5 PTS / Raynaud O19.5 PR",
      alphaEdge: "FADE",
      kellySizing: "5.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-08T14:03:00"),
    },

    // === MARCH 7, 2026 ===
    {
      id: uuidv4(),
      matchup: "Japan vs South Korea (WBC)",
      mathEv: -0.08,
      dissonanceScore: 0.50,
      prospectTheoryRead: "WBC total over - game fell short at 14 runs",
      selection: "Japan/Korea O14.5 @1.45",
      alphaEdge: "NEUTRAL",
      kellySizing: "2.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-07T06:41:00"),
    },

    // === MARCH 6, 2026 ===
    {
      id: uuidv4(),
      matchup: "Tennis: Osorio vs Jovic + Paul vs Bergs + Anisimova vs Blinkova + Mensik vs Giron + Eala vs Yastremska",
      mathEv: 0.08,
      dissonanceScore: 0.30,
      prospectTheoryRead: "Tennis 5-leg favorites parlay @2.86 - all covered",
      selection: "Osorio ML / Paul ML / Anisimova ML / Mensik ML / Eala ML",
      alphaEdge: "SHARP",
      kellySizing: "2.7%",
      actualOutcome: "WIN",
      timestamp: new Date("2026-03-06T23:26:00"),
    },
    {
      id: uuidv4(),
      matchup: "Tennis: Osaka vs Kasintseva + Jovic vs Osorio + Anisimova vs Blinkova + Eala vs Yastremska",
      mathEv: 0.04,
      dissonanceScore: 0.40,
      prospectTheoryRead: "Tennis 4-leg - Jovic upset killed it",
      selection: "Osaka ML / Jovic ML / Anisimova ML / Eala ML",
      alphaEdge: "NEUTRAL",
      kellySizing: "5.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-06T21:27:00"),
    },
    {
      id: uuidv4(),
      matchup: "HOU Rockets vs POR + Tennis + DEN Nuggets vs NY + PHX Suns vs NOP + SA Spurs vs LAC",
      mathEv: -0.25,
      dissonanceScore: 0.80,
      prospectTheoryRead: "10-leg NBA + Tennis mega parlay @17.06 - way too many legs",
      selection: "Rockets ML / Shapovalov ML / Nuggets ML / Suns ML / Jovic ML / Osaka ML / Spurs ML / Paul ML / Mensik ML / Eala ML",
      alphaEdge: "FADE",
      kellySizing: "2.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-06T21:23:00"),
    },
    {
      id: uuidv4(),
      matchup: "PHX Suns vs NOP + DEN Nuggets vs NY Knicks + SA Spurs vs LAC",
      mathEv: -0.05,
      dissonanceScore: 0.50,
      prospectTheoryRead: "NBA props + total 3-leg - Gordon PTS missed",
      selection: "Saddiq Bey O12.5 PTS / Aaron Gordon O7.5 PTS / Spurs/Clippers O211.5",
      alphaEdge: "NEUTRAL",
      kellySizing: "5.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-06T20:28:00"),
    },
    {
      id: uuidv4(),
      matchup: "Brazil vs USA (WBC)",
      mathEv: 0.12,
      dissonanceScore: 0.25,
      prospectTheoryRead: "WBC total over - blowout game hit easily",
      selection: "Brazil/USA O16.5 @1.90",
      alphaEdge: "SHARP",
      kellySizing: "2.5%",
      actualOutcome: "WIN",
      timestamp: new Date("2026-03-06T20:32:00"),
    },
    {
      id: uuidv4(),
      matchup: "CHA Hornets vs MIA Heat + HOU Rockets vs POR Blazers + DEN Nuggets vs NY Knicks + SA Spurs vs LAC",
      mathEv: 0.01,
      dissonanceScore: 0.45,
      prospectTheoryRead: "NBA 4-leg ML/spread/total mix @3.70 - Hornets & Nuggets lost",
      selection: "Hornets ML / Blazers +13.5 / Nuggets/Knicks O222.5 / Spurs ML",
      alphaEdge: "NEUTRAL",
      kellySizing: "7.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-06T18:45:00"),
    },
    {
      id: uuidv4(),
      matchup: "Tennis: FAA vs Monfils + Joint vs Cristian + Shapovalov vs Etcheverry + Jovic vs Osorio + Osaka vs Kasintseva",
      mathEv: -0.05,
      dissonanceScore: 0.55,
      prospectTheoryRead: "Tennis 5-leg @4.13 - Jovic upset killed it",
      selection: "FAA ML / Joint ML / Shapovalov ML / Jovic ML / Osaka ML",
      alphaEdge: "NEUTRAL",
      kellySizing: "5.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-06T19:56:00"),
    },
    {
      id: uuidv4(),
      matchup: "Tennis: Shelton vs Opelka + Gauff vs Rakhimova + FAA vs Monfils + Tiafoe vs Brooksby",
      mathEv: 0.02,
      dissonanceScore: 0.40,
      prospectTheoryRead: "Tennis 4-leg with games total prop @2.41",
      selection: "Shelton ML / Gauff ML / FAA ML / Brooksby/Tiafoe O20.5 games",
      alphaEdge: "NEUTRAL",
      kellySizing: "3.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-06T17:49:00"),
    },
    {
      id: uuidv4(),
      matchup: "Tennis: FAA vs Monfils + Joint vs Cristian + Brooksby vs Tiafoe + Shapovalov vs Etcheverry",
      mathEv: -0.10,
      dissonanceScore: 0.60,
      prospectTheoryRead: "Tennis 4-leg @5.95 - Brooksby upset killed it",
      selection: "FAA ML / Joint ML / Brooksby ML / Shapovalov ML",
      alphaEdge: "NEUTRAL",
      kellySizing: "2.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-06T18:34:00"),
    },
    {
      id: uuidv4(),
      matchup: "Tennis + WBC: Kalinskaya + Musetti + Sabalenka + FAA + Puerto Rico + Brooksby + Dominican Rep + Jovic",
      mathEv: -0.15,
      dissonanceScore: 0.70,
      prospectTheoryRead: "8-leg mixed Tennis/WBC @9.51 - too many legs",
      selection: "Kalinskaya ML / Musetti ML / Sabalenka ML / FAA ML / Puerto Rico ML / Brooksby +1.5 / DR ML / Jovic ML",
      alphaEdge: "FADE",
      kellySizing: "2.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-06T16:02:00"),
    },
    {
      id: uuidv4(),
      matchup: "Tennis: Shelton + Kalinskaya + Musetti + Sabalenka + Gauff + FAA + Jovic + Osaka",
      mathEv: -0.08,
      dissonanceScore: 0.60,
      prospectTheoryRead: "Tennis 8-leg heavy favorites @4.61 - one upset kills all",
      selection: "Shelton ML / Kalinskaya ML / Musetti ML / Sabalenka ML / Gauff ML / FAA ML / Jovic ML / Osaka ML",
      alphaEdge: "NEUTRAL",
      kellySizing: "3.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-06T16:10:00"),
    },
    {
      id: uuidv4(),
      matchup: "WBC + Soccer: Panama + Bayern + PSG + Real Madrid",
      mathEv: 0.05,
      dissonanceScore: 0.30,
      prospectTheoryRead: "Mixed 4-leg: WBC handicap + European soccer @2.70",
      selection: "Panama +4.5 / Bayern ML / PSG/Monaco O2.5 / Celta/RM O1.5",
      alphaEdge: "SHARP",
      kellySizing: "5.0%",
      actualOutcome: "WIN",
      timestamp: new Date("2026-03-06T10:37:00"),
    },
    {
      id: uuidv4(),
      matchup: "WBC + Tennis: Panama + Venezuela + GB/Mexico + Mboko + Raducanu + Sabalenka + Puerto Rico + DR + USA + Osaka",
      mathEv: -0.20,
      dissonanceScore: 0.80,
      prospectTheoryRead: "10-leg WBC + Tennis mega @12.74 - too ambitious",
      selection: "Panama +3.5 / Venezuela ML / GB +4.5 / Mboko ML / Raducanu ML / Sabalenka ML / Puerto Rico ML / DR ML / USA ML / Osaka ML",
      alphaEdge: "FADE",
      kellySizing: "2.0%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-06T09:49:00"),
    },

    // === MARCH 5-6, 2026 ===
    {
      id: uuidv4(),
      matchup: "Tennis + WBC: Kopriva vs Zheng + Sierra vs Stearns + China Taipei vs Japan",
      mathEv: 0.06,
      dissonanceScore: 0.30,
      prospectTheoryRead: "3-leg Tennis/WBC mix @2.56 - all hit",
      selection: "Kopriva ML / Sierra ML / China Taipei/Japan O5.5",
      alphaEdge: "SHARP",
      kellySizing: "2.7%",
      actualOutcome: "WIN",
      timestamp: new Date("2026-03-06T01:01:00"),
    },
    {
      id: uuidv4(),
      matchup: "DEN Nuggets vs LA Lakers + SAC Kings vs NOP Pelicans",
      mathEv: 0.06,
      dissonanceScore: 0.30,
      prospectTheoryRead: "NBA 2-leg: Nuggets ML + Zion props - both covered",
      selection: "Nuggets ML / Zion Williamson O21.5 PTS",
      alphaEdge: "SHARP",
      kellySizing: "3.5%",
      actualOutcome: "WIN",
      timestamp: new Date("2026-03-05T23:36:00"),
    },
    {
      id: uuidv4(),
      matchup: "HOU Rockets vs GS Warriors + SA Spurs vs DET Pistons + PHX Suns vs CHI Bulls + DEN Nuggets vs LA Lakers + SAC Kings vs NOP Pelicans",
      mathEv: 0.15,
      dissonanceScore: 0.25,
      prospectTheoryRead: "NBA 5-leg spread parlay @12.27 - ALL covered, biggest win",
      selection: "Warriors +4.5 / Spurs -12.5 / Bulls +4.5 / Lakers +10.5 / Pelicans -1.5",
      alphaEdge: "SHARP",
      kellySizing: "2.5%",
      actualOutcome: "WIN",
      timestamp: new Date("2026-03-05T21:44:00"),
    },
    {
      id: uuidv4(),
      matchup: "MIN Timberwolves vs TOR Raptors + PHX Suns vs CHI Bulls",
      mathEv: 0.08,
      dissonanceScore: 0.30,
      prospectTheoryRead: "NBA 2-leg: Wolves ML + Bulls spread - both hit",
      selection: "Timberwolves ML / Bulls +10.5",
      alphaEdge: "SHARP",
      kellySizing: "5.3%",
      actualOutcome: "WIN",
      timestamp: new Date("2026-03-05T20:32:00"),
    },
    {
      id: uuidv4(),
      matchup: "Tennis: Cerundolo vs van de Zandschulp + Brady vs Ruzic + Korda vs Comesana + Kopriva vs Zheng",
      mathEv: -0.05,
      dissonanceScore: 0.50,
      prospectTheoryRead: "Tennis 4-leg @3.98 - Cerundolo won but parlay still lost",
      selection: "Cerundolo ML / Brady ML / Korda ML / Kopriva -1.5 sets",
      alphaEdge: "NEUTRAL",
      kellySizing: "2.5%",
      actualOutcome: "LOSS",
      timestamp: new Date("2026-03-05T21:38:00"),
    },
    {
      id: uuidv4(),
      matchup: "Tennis: Shevchenko + Dimitrov + Vekic + Baez + Bucsa + Michelsen + Siniakova",
      mathEv: 0.10,
      dissonanceScore: 0.35,
      prospectTheoryRead: "Tennis 7-leg favorites @8.64 - all covered cleanly",
      selection: "Shevchenko ML / Dimitrov ML / Vekic -1.5 sets / Baez ML / Bucsa ML / Michelsen ML / Siniakova ML",
      alphaEdge: "SHARP",
      kellySizing: "1.5%",
      actualOutcome: "WIN",
      timestamp: new Date("2026-03-05T16:18:00"),
    },
  ];

  await db.insert(trades).values(extendedTrades);
  console.log(`  Inserted ${extendedTrades.length} extended trades`);
  console.log("Extended history seed complete!");
  process.exit(0);
}

seedHistory2().catch((err) => {
  console.error("Extended seed failed:", err);
  process.exit(1);
});
